### ISSUE TITLE
Item duplication expoit

### ISSUE THREAD

**Issue by SmallJoker** [stujones11/clothing#13]
If 0.4.x compatibility is wanted, remove the `"clothing"` player inventory and move it to the player meta (attributes). Main issue is this code part which might origin from the bags mod: (item duplication each join)

https://github.com/stujones11/clothing/blob/3d55e5df92b74d147d3f87f582f83ed755bb7c27/init.lua#L97-L102

**Comment by stujones11** [comment]
I think the code originates from a very early version of my armor mod, thanks for letting me know :)

I do think that clothing duplication is much less of an issue than armor duplication since it is 'cheap' and lasts forever anyway. I will update to using player meta for this _and_ armor for the 5.0.0 release.

**Comment by SmallJoker** [comment]
I'll submit a PR for 0.4.x compatibility because this exploit allows duplicating _any_ ItemStack.

**Comment by stujones11** [comment]
Fixed by 6def55c3cdaebad30176a31be6728d23bc70ca1e
